; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32@6.12.0
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1
	framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-arduino-libs-3.0.1.zip
board = esp32-s3-devkitm-1
framework = arduino
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
build_unflags = -Werror
monitor_speed = 115200
lib_deps = 
	symlink://C:\Users\shubh\OneDrive\Documents\Arduino\AutomataMqtt
	symlink://C:\Users\shubh\OneDrive\Documents\PlatformIO\Projects\SDWebServer
	bblanchon/ArduinoJson@^7.2.0
	links2004/WebSockets@^2.6.1
	knolleary/PubSubClient@^2.8
	ESP32Async/AsyncTCP
	ESP32Async/ESPAsyncWebServer
	t-vk/ESP32 BLE Keyboard@^0.3.2
build_flags = 
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D BOARD_HAS_PSRAM=1
board_build.arduino.memory_type = qio_opi
upload_port = knob.local