// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen3.h"
#include "ui_Screen5.h"
#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen4.h"
#include "ui_Screen6.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1086829539);    // assets/frame_000_delay-0.04s.png
LV_IMG_DECLARE(ui_img_winter_png);    // assets/winter.png
LV_IMG_DECLARE(ui_img_sunny_png);    // assets/sunny.png

// FONTS
LV_FONT_DECLARE(ui_font_monoton20);
LV_FONT_DECLARE(ui_font_monoton26);
LV_FONT_DECLARE(ui_font_monoton30);
LV_FONT_DECLARE(ui_font_monoton32);
LV_FONT_DECLARE(ui_font_monoton36);
LV_FONT_DECLARE(ui_font_monoton40);
LV_FONT_DECLARE(ui_font_monoton44);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
