// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void selectedScreen5_cb(lv_event_t * e);
void selectedScreen1_cb(lv_event_t * e);
void roller1_cb(lv_event_t * e);
void screen1btn_cb(lv_event_t * e);
void selectedScreen2_cb(lv_event_t * e);
void sendAction1Click(lv_event_t * e);
void sendActionUpClick(lv_event_t * e);
void sendActionLeftClick(lv_event_t * e);
void sendAction3Click(lv_event_t * e);
void sendActionRightClick(lv_event_t * e);
void sendAction5Click(lv_event_t * e);
void sendAction9Click(lv_event_t * e);
void sendActionDownClick(lv_event_t * e);
void sendAction7Click(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
