// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

// void sendAction1Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void sendAction2Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void sendAction4Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void sendAction3Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void sendOptionSelect(lv_event_t * e)
// {
// 	// Your code here
// }

// void runbtnClick(lv_event_t * e)
// {
// 	// Your code here
// }

// void sendAction6Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void sendAction5Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void selectedScreen1_cb(lv_event_t * e)
// {
// 	// Your code here
// }

// void selectedScreen2_cb(lv_event_t * e)
// {
// 	// Your code here
// }

// void selectedScreen4_cb(lv_event_t * e)
// {
// 	// Your code here
// }

// void sendAction9Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void sendAction8Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void sendAction7Click(lv_event_t * e)
// {
// 	// Your code here
// }
