// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void selectedScreen1_cb(lv_event_t * e);
void selectedScreen2_cb(lv_event_t * e);
void sendAction1Click(lv_event_t * e);
void sendAction2Click(lv_event_t * e);
void sendAction4Click(lv_event_t * e);
void sendAction3Click(lv_event_t * e);
void sendAction6Click(lv_event_t * e);
void sendAction5Click(lv_event_t * e);
void sendAction9Click(lv_event_t * e);
void sendAction8Click(lv_event_t * e);
void sendAction7Click(lv_event_t * e);
void selectedScreen4_cb(lv_event_t * e);
void sendOptionSelect(lv_event_t * e);
void runbtnClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
