// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Arc5;
extern void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_EndLabel;
extern lv_obj_t * ui_StartLabel;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label26;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Button5;
extern lv_obj_t * uic_EndLabel;
extern lv_obj_t * uic_StartLabel;
extern lv_obj_t * uic_Label25;
extern lv_obj_t * uic_Label19;
extern lv_obj_t * uic_Label26;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

