// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Arc1;
extern void ui_event_Roller1(lv_event_t * e);
extern lv_obj_t * ui_Roller1;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_arcLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_arcLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

