// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_visibility;
lv_obj_t * uic_humidity;
lv_obj_t * uic_wind;
lv_obj_t * uic_sidetext;
lv_obj_t * uic_temp;
lv_obj_t * uic_datetext;
lv_obj_t * uic_areaname;
lv_obj_t * uic_img;
lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_img = NULL;
lv_obj_t * ui_areaname = NULL;
lv_obj_t * ui_datetext = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_sidetext = NULL;
lv_obj_t * ui_wind = NULL;
lv_obj_t * ui_humidity = NULL;
lv_obj_t * ui_visibility = NULL;
// event funtions
void ui_event_Screen6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen6, &ui_img_winter_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_img, &ui_img_sunny_png);
    lv_obj_set_width(ui_img, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_img, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_img, 0);
    lv_obj_set_y(ui_img, -50);
    lv_obj_set_align(ui_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_areaname = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_areaname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_areaname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_areaname, 0);
    lv_obj_set_y(ui_areaname, -140);
    lv_obj_set_align(ui_areaname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_areaname, "Hyderabad");
    lv_obj_set_style_text_color(ui_areaname, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_areaname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_areaname, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datetext = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_datetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_datetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_datetext, 0);
    lv_obj_set_y(ui_datetext, -110);
    lv_obj_set_align(ui_datetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_datetext, "Tuesday 18th Aug, 2025");
    lv_obj_set_style_text_color(ui_datetext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_datetext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, -30);
    lv_obj_set_y(ui_temp, 20);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "24");
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sidetext = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_sidetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sidetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sidetext, 46);
    lv_obj_set_y(ui_sidetext, 20);
    lv_obj_set_align(ui_sidetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sidetext, "Sunny\n28\n30");
    lv_obj_set_style_text_color(ui_sidetext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sidetext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wind = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_wind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wind, -90);
    lv_obj_set_y(ui_wind, 100);
    lv_obj_set_align(ui_wind, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wind, "Wind\n4km/h");
    lv_obj_set_style_text_color(ui_wind, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidity = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity, 0);
    lv_obj_set_y(ui_humidity, 100);
    lv_obj_set_align(ui_humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidity, "Humidity\n40%");
    lv_obj_set_style_text_color(ui_humidity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_visibility = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_visibility, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_visibility, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_visibility, 90);
    lv_obj_set_y(ui_visibility, 100);
    lv_obj_set_align(ui_visibility, LV_ALIGN_CENTER);
    lv_label_set_text(ui_visibility, "Visibility\n4km");
    lv_obj_set_style_text_color(ui_visibility, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_visibility, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);
    uic_img = ui_img;
    uic_areaname = ui_areaname;
    uic_datetext = ui_datetext;
    uic_temp = ui_temp;
    uic_sidetext = ui_sidetext;
    uic_wind = ui_wind;
    uic_humidity = ui_humidity;
    uic_visibility = ui_visibility;

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    uic_img = NULL;
    ui_img = NULL;
    uic_areaname = NULL;
    ui_areaname = NULL;
    uic_datetext = NULL;
    ui_datetext = NULL;
    uic_temp = NULL;
    ui_temp = NULL;
    uic_sidetext = NULL;
    ui_sidetext = NULL;
    uic_wind = NULL;
    ui_wind = NULL;
    uic_humidity = NULL;
    ui_humidity = NULL;
    uic_visibility = NULL;
    ui_visibility = NULL;

}
