// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_img;
extern lv_obj_t * ui_areaname;
extern lv_obj_t * ui_datetext;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_sidetext;
extern lv_obj_t * ui_wind;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_visibility;
// CUSTOM VARIABLES
extern lv_obj_t * uic_img;
extern lv_obj_t * uic_areaname;
extern lv_obj_t * uic_datetext;
extern lv_obj_t * uic_temp;
extern lv_obj_t * uic_sidetext;
extern lv_obj_t * uic_wind;
extern lv_obj_t * uic_humidity;
extern lv_obj_t * uic_visibility;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

